name: cfn-security sast

on: [push]

jobs:
  ## all scans
  security-scan-nag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: grolston/cfn-security@master
      with:
        cloudformation_directory: "./"
        scanner: "all"
    - name: setup & Run
      run: |
        ls -alrt
    - name: Archive the result so it can be downloaded
      uses: actions/upload-artifact@v3
      with:
        name: cnf-security-artifact
        path: ${{ github.workspace }}/cfn_security.sarif
  
