name: cfn-lint-action

on: [push]

jobs:
  cloudformation-linter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: cfn-lint-action
        uses: ScottBrenner/cfn-lint-action@v2
        with:
          version: 0.71.1

# cfn-lint template.yaml
# cfn-lint -t template.yaml

# Multiple files can be linted by either specifying multiple specific files:
# cfn-lint template1.yaml template2.yaml
# cfn-lint -t template1.yaml template2.yaml

# or by using wildcards (globbing):

# Lint all yaml files in path:
# cfn-lint path/*.yaml

# Lint all yaml files in path and all subdirectories (recursive):
# cfn-lint path/**/*.yaml


      - name: Run CFN Lint
        continue-on-error: true
        run: |
          cfn-lint -t single-instance.json -b --custom-rules cfn_lint_custom_rule.txt -f sarif --output-file cfn_lint.sarif
         
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2.1.32
        with:
          sarif_file: cfn_lint.sarif  

      - name: Archive the result so it can be downloaded
        uses: actions/upload-artifact@v3
        with:
          name: cnf-lint-artifact
          path: ${{ github.workspace }}/cfn_lint.sarif
