name: cfn-lint-action

on: [push]

jobs:
  cloudformation-linter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: cfn-lint-action
        uses: ScottBrenner/cfn-lint-action@v2.2.8


      - name: Run CFN Lint
        continue-on-error: true
        run: |
          ls -altr
          pwd
          cfn-lint -t *.yml -f sarif -b -z cfn_custom_rule.txt > cfn_lint.sarif 
          cat cfn_lint.sarif
          cat cfn_custom_rule.txt
         
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: cfn_lint.sarif  

      - name: Archive the result so it can be downloaded
        uses: actions/upload-artifact@v3
        with:
          name: cnf-lint-artifact
          path: ${{ github.workspace }}/cfn_lint.sarif
