name: cfn-lint-action

on: [push]

jobs:
  cloudformation-linter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: cfn-lint-action
        uses: ScottBrenner/cfn-lint-action@v2.2.8


      - name: Print the Cloud Formation Linter Version & run Linter.
        run: |
          SETOPT -s globstar
          cfn-lint --version
          cfn-lint -t -g *.yml            
