name: cfn-lint-action

on: [push]

jobs:
  cloudformation-linter:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: cfn-lint-action
        uses: ScottBrenner/cfn-lint-action@v2.2.8


      - name: Print the Cloud Formation Linter Version & run Linter.
        run: |
          cfn-lint -t *.yml -f sarif -g -i
          pwd
          ls -altr
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif        
