name: cfn-nag-action

on: [push]

jobs:
  cloudformation-linter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: setup & Run
        uses: stelligent/cfn_nag@master
        with:
          input_path: .
          extra_args: --fail-on-warnings
