name: Snyk Analysis
on: push
jobs:
  snyk-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Snyk to check configuration files for security issues
        continue-on-error: true
        uses: snyk/actions/iac@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
# cfn-lint template.yaml
# cfn-lint -t template.yaml

# Multiple files can be linted by either specifying multiple specific files:
# cfn-lint template1.yaml template2.yaml
# cfn-lint -t template1.yaml template2.yaml

# or by using wildcards (globbing):

# Lint all yaml files in path:
# cfn-lint path/*.yaml

# Lint all yaml files in path and all subdirectories (recursive):
# cfn-lint path/**/*.yaml

          file: .
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif
